# Trigger the workflow on push or pull request
on: [push, pull_request]
jobs:
  test_runner:
    name: gempytf CI test
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          activate-environment: gempytf 
          environment-file: env_nogpu.yml
          python-version: 3.8
          channels: conda-forge,defaults
          channel-priority: true
          auto-update-conda: true
          use-only-tar-bz2: true
      - name: install baryte
        shell: bash -l {0}
        run: pip install -e .
      - name: conda info
        shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: run tests
        shell: bash -l {0}
        run: pytest .
